version: "3"
services:
#  hackaton-postgres:
#    container_name: hackaton-postgres
#    image: postgres:16.2-alpine3.19
#    environment:
#      POSTGRES_DB: conversation_analysis
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root
#      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
#      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
#    expose:
#      - "5432"
#    ports:
#      - "5432:5432"
#    networks:
#      - conversation_analysis_network
#    restart: unless-stopped
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  hackaton-backend:
    build: ./backend
    container_name: hackaton-backend
    ports:
      - "8080:8080"
    networks:
      - hack_network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped

#  hackaton-ml:
#    build: ./ml
#    container_name: hackaton-ml
#    ports:
#      - "8001:8000"
#    networks:
#      - conversation_analysis_network
#    environment:
#      - TZ=Europe/Moscow
#    depends_on:
#      - hackaton-postgres
#    restart: unless-stopped

networks:
  hack_network:
