version: "3"
services:
  hackaton-postgres:
    container_name: hackaton-postgres
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: rutube
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rYihCMkc
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - hack_network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data


  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  hackaton-backend:
    build: ./backend
    container_name: hackaton-backend
    ports:
      - "8080:8080"
    networks:
      - hack_network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped

  hackaton-tgbot:
    build: ./telegram
    container_name: hackaton-tgbot
    ports:
      - "8000:8000"
    networks:
      - hack_network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped

#  hackaton-ml:
#    build: ./ml
#    container_name: hackaton-ml
#    ports:
#      - "8001:8001"
#    networks:
#      - hack_network
#    environment:
#      - TZ=Europe/Moscow
##    depends_on:
##      - hackaton-postgres
#    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - hack_network
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: rYihCMkc
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - hack_network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - hack_network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=rYihCMkc
    restart: unless-stopped

networks:
  hack_network:

volumes:
  minio_data:
  prometheus_data:
  postgres_data: